language: rust

before_script:
  - sudo add-apt-repository ppa:terry.guo/gcc-arm-embedded -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-arm-none-eabi

script:
    - cargo build --target thumbv7m-none-eabi --features stk3700
    - cargo build --target thumbv7m-none-eabi --features dk3750
